---
# tasks file for ansible-role-landir.fonts
- name: Update apt cache (Debian).
  apt: update_cache=true cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Enable universe repository
    apt_repository:
      repo: "{{ item }}"
    loop:
      - "deb http://archive.ubuntu.com/ubuntu/ {{ distro-name }} universe"
      - "deb http://archive.ubuntu.com/ubuntu/ {{ distro-name }}-updates universe"
      - "deb http://security.ubuntu.com/ubuntu/ {{ distro-name }}-security universe"
  changed_when: false

- name: Packages for fonts.
  apt:
    name:
      - fonts-powerline
      - fontconfig
      - fonts-firacode
    state: present
  when: ansible_os_family == 'Debian'

- name: Folder of fonts.
  file:
    dest: "{{ fonte_usuario_home }}"
    state: directory
    owner: "{{ fonte_usuario }}"
  ignore_errors: yes
  become: false

- name: Repo of powerline-fonts
  git:
    repo: 'https://github.com/powerline/fonts.git'
    dest: "{{ fonte_usuario_home }}"
    #update=yes
    #force=yes
  notify: "restarted font-cache"
  become: false

